function Swipe(v,e){function y(){g=c.children;C=g.length;2>g.length&&(e.continuous=!1);p.transitions&&e.continuous&&2==g.length&&(c.appendChild(g[0].cloneNode(!0)),c.appendChild(g[1].cloneNode(!0)),g=c.children);m=Array(g.length);d=v.getBoundingClientRect().width||v.offsetWidth||e.width;c.style.width=g.length*d+"px";for(var b=g.length;b--;){var q=g[b];q.style.width=d+"px";q.setAttribute("data-index",b);p.transitions&&(q.style.left=b*-d+"px",h(b,a>b?-d:a<b?d:0,0))}e.continuous&&p.transitions&&(h(k(a-
1),-d,0),h(k(a+1),d,0));p.transitions||(c.style.left=a*-d+"px");v.style.visibility="visible"}function z(){e.continuous?w(a+1):a<g.length-1&&w(a+1)}function k(b){return(g.length+b%g.length)%g.length}function w(b,q){if(a!=b){if(p.transitions){var c=Math.abs(a-b)/(a-b);if(e.continuous){var f=c,c=-m[k(b)]/d;c!==f&&(b=-c*g.length+b)}for(f=Math.abs(a-b)-1;f--;)h(k((b>a?b:a)-f-1),d*c,0);b=k(b);h(a,d*c,q||n);h(b,0,q||n);e.continuous&&h(k(b-c),-(d*c),0)}else b=k(b),G(a*-d,b*-d,q||n);a=b;c=e.callback&&e.callback(a,
g[a]);setTimeout(c||A,0)}}function h(b,a,c){r(b,a,c);m[b]=a}function r(b,a,c){if(b=(b=g[b])&&b.style)b.webkitTransitionDuration=b.MozTransitionDuration=b.msTransitionDuration=b.OTransitionDuration=b.transitionDuration=c+"ms",b.webkitTransform="translate("+a+"px,0)translateZ(0)",b.msTransform=b.MozTransform=b.OTransform="translateX("+a+"px)"}function G(b,d,f){if(f)var h=+new Date,k=setInterval(function(){var l=+new Date-h;l>f?(c.style.left=d+"px",s&&(x=setTimeout(z,s)),e.transitionEnd&&e.transitionEnd.call(event,
a,g[a]),clearInterval(k)):c.style.left=Math.floor(l/f*100)/100*(d-b)+b+"px"},4);else c.style.left=d+"px"}function t(){clearTimeout(x);x=null}var A=function(){},p={addEventListener:!!window.addEventListener,touch:"ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,transitions:function(b){var a=["transitionProperty","WebkitTransition","MozTransition","OTransition","msTransition"],c;for(c in a)if(void 0!==b.style[a[c]])return!0;return!1}(document.createElement("swipe"))};
if(v){var c=v.children[0],g,m,d,C;e=e||{};var a=parseInt(e.startSlide,10)||0,n=e.speed||300;e.continuous=void 0!==e.continuous?e.continuous:!0;var s=e.auto||0,x,D,E,F,f,B,u,l={handleEvent:function(b){switch(b.type){case "touchstart":this.start(b);break;case "touchmove":this.move(b);break;case "touchend":var a=this.end(b);setTimeout(a||A,0);break;case "webkitTransitionEnd":case "msTransitionEnd":case "oTransitionEnd":case "otransitionend":case "transitionend":a=this.transitionEnd(b);setTimeout(a||
A,0);break;case "resize":setTimeout(y||A,0)}e.stopPropagation&&b.stopPropagation()},start:function(a){a=a.touches[0];D=a.pageX;E=a.pageY;F=+new Date;B=f=u=void 0;c.addEventListener("touchmove",this,!1);c.addEventListener("touchend",this,!1)},move:function(b){if(!(1<b.touches.length||b.scale&&1!==b.scale)){e.disableScroll&&b.preventDefault();var c=b.touches[0];f=c.pageX-D;B=c.pageY-E;"undefined"==typeof u&&(u=!!(u||Math.abs(f)<Math.abs(B)));u||(b.preventDefault(),t(),e.continuous?(r(k(a-1),f+m[k(a-
1)],0),r(a,f+m[a],0),r(k(a+1),f+m[k(a+1)],0)):(f/=!a&&0<f||a==g.length-1&&0>f?Math.abs(f)/d+1:1,r(a-1,f+m[a-1],0),r(a,f+m[a],0),r(a+1,f+m[a+1],0)))}},end:function(b){b=250>Number(+new Date-F)&&20<Math.abs(f)||Math.abs(f)>d/2;var q=!a&&0<f||a==g.length-1&&0>f;e.continuous&&(q=!1);var p=0>f;u||(b&&!q?(p?(e.continuous?(h(k(a-1),-d,0),h(k(a+2),d,0)):h(a-1,-d,0),h(a,m[a]-d,n),h(k(a+1),m[k(a+1)]-d,n),a=k(a+1)):(e.continuous?(h(k(a+1),d,0),h(k(a-2),-d,0)):h(a+1,d,0),h(a,m[a]+d,n),h(k(a-1),m[k(a-1)]+d,n),
a=k(a-1)),e.callback&&e.callback(a,g[a])):e.continuous?(h(k(a-1),-d,n),h(a,0,n),h(k(a+1),d,n)):(h(a-1,-d,n),h(a,0,n),h(a+1,d,n)));c.removeEventListener("touchmove",l,!1);c.removeEventListener("touchend",l,!1)},transitionEnd:function(b){parseInt(b.target.getAttribute("data-index"),10)==a&&(s&&(x=setTimeout(z,s)),e.transitionEnd&&e.transitionEnd.call(b,a,g[a]))}};y();s&&(x=setTimeout(z,s));p.addEventListener?(p.touch&&c.addEventListener("touchstart",l,!1),p.transitions&&(c.addEventListener("webkitTransitionEnd",
l,!1),c.addEventListener("msTransitionEnd",l,!1),c.addEventListener("oTransitionEnd",l,!1),c.addEventListener("otransitionend",l,!1),c.addEventListener("transitionend",l,!1)),window.addEventListener("resize",l,!1)):window.onresize=function(){y()};return{setup:function(){y()},slide:function(a,c){t();w(a,c)},prev:function(){t();e.continuous?w(a-1):a&&w(a-1)},next:function(){t();z()},stop:function(){t()},getPos:function(){return a},getNumSlides:function(){return C},kill:function(){t();c.style.width=
"";c.style.left="";for(var a=g.length;a--;){var d=g[a];d.style.width="";d.style.left="";p.transitions&&r(a,0,0)}p.addEventListener?(c.removeEventListener("touchstart",l,!1),c.removeEventListener("webkitTransitionEnd",l,!1),c.removeEventListener("msTransitionEnd",l,!1),c.removeEventListener("oTransitionEnd",l,!1),c.removeEventListener("otransitionend",l,!1),c.removeEventListener("transitionend",l,!1),window.removeEventListener("resize",l,!1)):window.onresize=null}}}};
