(function(){var h={},mt={},c={id:"90135e6da53b8975e78f61da963540d2",dm:["ayhl.oldzr.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],icon:'',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'',hca:'731D45257E50B107',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,s=!0,t=null,w=!1;mt.cookie={};mt.cookie.set=function(b,a,g){var d;g.J&&(d=new Date,d.setTime(d.getTime()+g.J));document.cookie=b+"="+a+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(d?"; expires="+d.toGMTString():"")+(g.$b?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};
mt.cookie.xb=function(b,a){try{var g="Hm_ck_"+ +new Date;mt.cookie.set(g,"is-cookie-enabled",{domain:b,path:a,J:r});var d="is-cookie-enabled"===mt.cookie.get(g)?"1":"0";mt.cookie.set(g,"",{domain:b,path:a,J:-1});return d}catch(f){return"0"}};mt.lang={};mt.lang.e=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};mt.lang.Da=function(b){return mt.lang.e(b,"Number")&&isFinite(b)};mt.lang.ia=function(){return mt.lang.e(c.aet,"String")};
mt.lang.h=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.H=function(b,a){var g=w;if(b==t||!mt.lang.e(b,"Array")||a===r)return g;if(Array.prototype.indexOf)g=-1!==b.indexOf(a);else for(var d=0;d<b.length;d++)if(b[d]===a){g=s;break}return g};
(function(){var b=mt.lang;mt.f={};mt.f.xa=function(a){return document.getElementById(a)};mt.f.eb=function(a){if(!a)return t;try{for(var b=a.split(">"),d=document.body,f=b.length-1;0<=f;f--)if(-1<b[f].indexOf("#")){var e=b[f].split("#")[1];(d=document.getElementById(e))||(d=document.getElementById(decodeURIComponent(e)));b=b.splice(f+1,b.length-(f+1));break}for(a=0;d&&a<b.length;){var n=String(b[a]).toLowerCase();if(!("html"===n||"body"===n)){var f=0,m=b[a].match(/\[(\d+)\]/i),e=[];if(m)f=m[1]-1,n=
n.split("[")[0];else if(1!==d.childNodes.length){for(var p=0,v=0,k=d.childNodes.length;v<k;v++){var l=d.childNodes[v];1===l.nodeType&&l.nodeName.toLowerCase()===n&&p++;if(1<p)return t}if(1!==p)return t}for(p=0;p<d.childNodes.length;p++)1===d.childNodes[p].nodeType&&d.childNodes[p].nodeName.toLowerCase()===n&&e.push(d.childNodes[p]);if(!e[f])return t;d=e[f]}a++}return d}catch(q){return t}};mt.f.ga=function(a,b){var d=[],f=[];if(!a)return f;for(;a.parentNode!=t;){for(var e=0,n=0,m=a.parentNode.childNodes.length,
p=0;p<m;p++){var v=a.parentNode.childNodes[p];if(v.nodeName===a.nodeName&&(e++,v===a&&(n=e),0<n&&1<e))break}if((m=""!==a.id)&&b){d.unshift("#"+encodeURIComponent(a.id));break}else m&&(m="#"+encodeURIComponent(a.id),m=0<d.length?m+">"+d.join(">"):m,f.push(m)),d.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<e?"["+n+"]":""));a=a.parentNode}f.push(d.join(">"));return f};mt.f.jb=function(a){return(a=mt.f.ga(a,s))&&a.length?String(a[0]):""};mt.f.ib=function(a){return mt.f.ga(a,w)};mt.f.Ub=
function(a,b){for(b=b.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.f.cb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Vb=function(a){var b={top:0,left:0};if(!a)return b;var d=mt.f.cb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());return{top:b.top+(window.pageYOffset||d.scrollTop)-(d.clientTop||0),left:b.left+(window.pageXOffset||d.scrollLeft)-(d.clientLeft||0)}};mt.f.getAttribute=function(a,
b){var d=a.getAttribute&&a.getAttribute(b)||t;if(!d&&a.attributes&&a.attributes.length)for(var f=a.attributes,e=f.length,n=0;n<e;n++)f[n].nodeName===b&&(d=f[n].nodeValue);return d};mt.f.R=function(a){var b="document";a.tagName!==r&&(b=a.tagName);return b.toLowerCase()};mt.f.mb=function(a){var g="";a.textContent?g=b.trim(a.textContent):a.innerText&&(g=b.trim(a.innerText));g&&(g=g.replace(/\s+/g," ").substring(0,255));return g};mt.f.ya=function(a,b){var d=mt.f.R(a);"input"===d&&b&&("button"===a.type||
"submit"===a.type)?d=a.value||"":"input"===d&&!b&&"password"!==a.type?d=a.value||"":"img"===d?(d=mt.f.getAttribute,d=d(a,"alt")||d(a,"title")||d(a,"src")):d="body"===d||"html"===d?["(hm-default-content-for-",d,")"].join(""):mt.f.mb(a);return String(d).substring(0,255)};(function(){(mt.f.Ab=function(){function a(){if(!a.U){a.U=s;for(var d=0,b=f.length;d<b;d++)f[d]()}}function b(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(b,1);return}a()}var d=w,f=[],e;document.addEventListener?
e=function(){document.removeEventListener("DOMContentLoaded",e,w);a()}:document.attachEvent&&(e=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",e),a())});(function(){if(!d)if(d=s,"complete"===document.readyState)a.U=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",e,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",e);window.attachEvent("onload",a);var f=w;try{f=window.frameElement==
t}catch(m){}document.documentElement.doScroll&&f&&b()}})();return function(d){a.U?d():f.push(d)}}()).U=w})();return mt.f})();mt.event={};mt.event.d=function(b,a,g){b.attachEvent?b.attachEvent("on"+a,function(a){g.call(b,a)}):b.addEventListener&&b.addEventListener(a,g,w)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=w};
(function(){var b=mt.event;mt.i={};mt.i.Ca=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.i.vb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.i.cookieEnabled=navigator.cookieEnabled;mt.i.javaEnabled=navigator.javaEnabled();mt.i.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.i.Db=(window.screen.width||0)+"x"+(window.screen.height||0);mt.i.colorDepth=window.screen.colorDepth||0;mt.i.S=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.i.L=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.i.orientation=0;(function(){function a(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.i.orientation=a}a();b.d(window,"orientationchange",a)})();return mt.i})();
mt.o={};mt.o.parse=function(b){return(new Function("return ("+b+")"))()};
mt.o.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=g[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return b(d);case "boolean":return String(d);
default:if(d===t)return"null";if(d instanceof Array){var f=["["],e=d.length,n,m,g;for(m=0;m<e;m++)switch(g=d[m],typeof g){case "undefined":case "function":case "unknown":break;default:n&&f.push(","),f.push(mt.o.stringify(g)),n=1}f.push("]");return f.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+a(d.getMonth()+1)+"-"+a(d.getDate())+"T"+a(d.getHours())+":"+a(d.getMinutes())+":"+a(d.getSeconds())+'"';n=["{"];m=mt.o.stringify;for(e in d)if(Object.prototype.hasOwnProperty.call(d,e))switch(g=
d[e],typeof g){case "undefined":case "unknown":case "function":break;default:f&&n.push(","),f=1,n.push(m(e)+":"+m(g))}n.push("}");return n.join("")}}}();mt.localStorage={};mt.localStorage.Y=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(b){return w}return s};
mt.localStorage.set=function(b,a,g){var d=new Date;d.setTime(d.getTime()+g||31536E6);try{window.localStorage?(a=d.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.Y()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(b,a),mt.localStorage.l.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),g=b.substring(0,a)-0;if(g&&g>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.Y())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(b)}catch(d){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.Y())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(b),mt.localStorage.l.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(g){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Ka={};mt.Ka.log=function(b,a){var g=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=g;g.onload=function(){g.onload=t;g=window[d]=t;a&&a(b)};g.src=b};mt.oa={};
mt.oa.nb=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return b};
mt.oa.Tb=function(b,a,g,d,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+g+'" height="'+d+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+g+'" height="'+d+'" src="'+a+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.m=function(b,a){var g=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return g?g[3]:t};mt.url.Wb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.gb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.K=function(b){return(b=mt.url.gb(b))?b.replace(/:\d+$/,""):b};mt.url.ga=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=w,b=document.getElementsByTagName("script"),d=b.length,d=100<d?100:d,f=0;f<d;f++){var e=b[f].src;if(e&&0===e.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.bb=b})();var A=h.bb;
h.z={Xb:"http://tongji.baidu.com/hm-web/welcome/ico",Ha:"hm.baidu.com/hm.gif",Ra:/^(tongji|hmcdn).baidu.com$/,Ma:"tongji.baidu.com",rb:"hmmd",tb:"hmpl",Nb:"utm_medium",qb:"hmkw",Pb:"utm_term",ob:"hmci",Mb:"utm_content",ub:"hmsr",Ob:"utm_source",pb:"hmcu",Lb:"utm_campaign",I:0,D:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",la:A()||"https:"===document.location.protocol?"https:":"http:",Yb:0,Rb:6E5,yb:6E5,Zb:5E3,Sb:5,ba:1024,Qb:1,V:2147483647,La:"hca bs kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt hh".split(" "),
M:s,ua:["a","input","button"],Ta:{id:"data-hm-id",aa:"data-hm-class",ra:"data-hm-xpath",content:"data-hm-content",pa:"data-hm-tag",link:"data-hm-link"},ta:"data-hm-enabled",sa:"data-hm-disabled",zb:"https://hmcdn.baidu.com/static/tongji/plugins/",Ga:["UrlChangeTracker"]};(function(){var b={A:{},d:function(a,b){this.A[a]=this.A[a]||[];this.A[a].push(b)},F:function(a,b){this.A[a]=this.A[a]||[];for(var d=this.A[a].length,f=0;f<d;f++)this.A[a][f](b)}};return h.G=b})();
(function(){function b(b,d){var f=document.createElement("script");f.charset="utf-8";a.e(d,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=t,d()}:f.onload=function(){d()});f.src=b;var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(f,e)}var a=mt.lang;return h.load=b})();
(function(){var b=mt.lang,a=mt.f,g={P:function(d,b){return function(e){var n=e.target||e.srcElement;if(n){var m=n.getAttribute(d.X);e=e.clientX+":"+e.clientY;if(m&&m===e)n.removeAttribute(d.X);else if(b&&0<b.length&&(n=a.ib(n))&&n.length)if(m=n.length,e=n[n.length-1],1E4>m*e.split(">").length)for(e=0;e<m;e++)g.Ja(d,n[e]);else g.Ja(d,e)}}},Ja:function(a,f){for(var e={},n=String(f).split(">").length,m=0;m<n;m++)e[f]="",f=f.substring(0,f.lastIndexOf(">"));a&&(b.e(a,"Object")&&a.va)&&a.va(e)},Bb:function(a,
b){return function(e){(e.target||e.srcElement).setAttribute(a.X,e.clientX+":"+e.clientY);a&&a.r&&(b?a.r(b):a.r("#"+encodeURIComponent(this.id),e.type))}}};return h.da=g})();
(function(){var b=mt.f,a=mt.o,g=mt.event,d=mt.lang,f=h.da,e={X:"HM_ce",Na:function(){if(c.cetrk&&c.cetrk.length){g.d(document,"click",f.P(e,c.cetrk));for(var d=0,m=c.cetrk.length;d<m;d++){var p;try{p=a.parse(decodeURIComponent(String(c.cetrk[d])))}catch(v){p={}}var k=p.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=b.xa(k))&&g.d(k,"click",f.Bb(e,p)))}}},va:function(b){if(c.cetrk&&c.cetrk.length)for(var d=0,f=c.cetrk.length;d<f;d++){var g;try{g=a.parse(decodeURIComponent(String(c.cetrk[d])))}catch(k){g=
{}}b.hasOwnProperty(g.p)&&e.r(g)}},r:function(a){h.c.b.et=7;var f=a&&a.k||"",f=d.h(f),e=[];if(a&&a.a&&d.e(a.a,"Object"))for(var g in a.a)if(a.a.hasOwnProperty(g)){e.push(d.h(g));var k=b.eb(a.a[g]||""),k=k?b.ya(k,w):"";e.push(d.h(k))}a="";e.length&&(a="*"+e.join("*"));h.c.b.ep="ce!_iden*"+f+a;h.c.j()}};h.G.d("pv-b",e.Na);return e})();
(function(){var b=mt.lang,a=mt.f,g=mt.event,d=mt.i,f=h.z,e=h.G,n=+new Date,m=[],p={P:function(){return function(d){if(h.c&&h.c.M&&c.aet&&c.aet.length){var k=d.target||d.srcElement;if(k){var l=h.c.ua,q=a.getAttribute(k,f.ta)!=t?s:w;if(a.getAttribute(k,f.sa)==t)if(q)p.Z(p.fa(k,d));else{var e=a.R(k);if(b.H(l,"*")||b.H(l,e))p.Z(p.fa(k,d));else for(;k.parentNode!=t;){var q=k.parentNode,e=a.R(q),g="a"===e&&b.H(l,"a")?s:w,e="button"===e&&b.H(l,"button")?s:w,u=a.getAttribute(q,f.ta)!=t?s:w;if(a.getAttribute(q,
f.sa)==t&&(g||e||u)){p.Z(p.fa(q,d));break}k=k.parentNode}}}}}},fa:function(e,k){var l={},q=f.Ta;l.id=a.getAttribute(e,q.id)||a.getAttribute(e,"id")||"";l.aa=a.getAttribute(e,q.aa)||a.getAttribute(e,"class")||"";l.ra=a.getAttribute(e,q.ra)||a.jb(e);l.content=a.getAttribute(e,q.content)||a.ya(e,s);l.pa=a.getAttribute(e,q.pa)||a.R(e);l.link=a.getAttribute(e,q.link)||a.getAttribute(e,"href")||"";l.type=k.type||"click";q=b.Da(e.offsetTop)?e.offsetTop:0;"click"===k.type?q=d.Ca?k.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):k.pageY:"touchend"===k.type&&(k.ma&&b.e(k.ma.changedTouches,"Array")&&k.ma.changedTouches.length)&&(q=k.ma.changedTouches[0].pageY);l.Kb=q;return l},Z:function(a){var d=b.h;a=[+new Date-(h.c.B!==r?h.c.B:n),d(a.id),d(a.aa),d(a.pa),d(a.ra),d(a.link),d(a.content),a.type,a.Kb].join("*");p.$(a);b.e(this.O(),"Function")&&this.O()()},$:function(a){a.length>f.ba||(encodeURIComponent(m.join("!")+a).length>f.ba&&(p.r(m.join("!")),m=[]),m.push(a))},r:function(a){h.c.b.et=5;h.c.b.ep=
a;h.c.j()},O:function(){return function(){m&&m.length&&(p.r(m.join("!")),m=[])}}};b.ia()&&""!==c.aet&&e.d("pv-b",function(){g.d(document,"click",p.P());"ontouchend"in document&&g.d(window,"touchend",p.P());g.d(window,"unload",p.O())});return p})();
(function(){var b=mt.event,a=mt.i,g=h.z,d=h.G,f=+new Date,e=[],n=t,m={Za:function(){return function(){h.c&&(h.c.M&&c.aet&&c.aet.length)&&(window.clearTimeout(n),n=window.setTimeout(function(){m.Pa(a.S()+a.L())},150))}},Pa:function(a){m.$([+new Date-(h.c.B!==r?h.c.B:f),a].join("*"))},$:function(a){if(encodeURIComponent(e.join("!")+a).length>g.ba||3<e.length)m.r(e.join("!")),e=[];e.push(a)},r:function(d){h.c.b.et=6;h.c.b.vh=a.L();h.c.b.ep=d;h.c.j()},O:function(){return function(){e&&e.length&&(m.r(e.join("!")),
e=[])}}};mt.lang.ia()&&""!==c.aet&&d.d("pv-b",function(){b.d(window,"scroll",m.Za());b.d(window,"unload",m.O())});return m})();
(function(){function b(){function a(d){function e(){}for(var g=s,k=0,l=0,q=t,y=t,z=d.length,u=0,x=t,k=0;k<z;k++)if(q=d[k],q.chromeVer===n){g=s;y=q.tests;u=y.length;for(l=0;l<u;l++)if(e=b[y[l].name],e()!==y[l].expect){g=w;break}if(u&&g){x={name:"360browser",type:q.type,version:q.ver};break}}return x}var d=[];d.push({ver:"8.3",type:"fast",tests:[{name:"seamlessiframe",expect:1}],chromeVer:"42"});var b={pointerevents:function(){return"maxTouchPoints"in window.navigator?1:"msMaxTouchPoints"in window.navigator||
"mozMaxTouchPoints"in window.navigator||"webkitMaxTouchPoints"in window.navigator?9:0},webgl3D:function(){for(var a="webgl ms-webgl experimental-webgl moz-webgl opera-3d webkit-3d ms-3d 3d".split(" "),d=a.length,b="",e=document.createElement("canvas"),l=w,q=0;q<d;q++)try{if(e.getContext(a[q])){l=s;b=a[q];break}}catch(f){}return l?"webgl"===b?1:9:0},seamlessiframe:function(){return"seamless"in document.createElement("iframe")?1:0},speechsynthesis:function(){return"speechSynthesis"in window?1:"webkitSpeechSynthesis"in
window||"mozSpeechSynthesis"in window||"oSpeechSynthesis"in window||"msSpeechSynthesis"in window?9:0}},e=t,n=function(){var a=navigator.userAgent.toLowerCase().match(/chrome\/(\d+)/i);return a?a[1]:"-1"}();"-1"!==n&&(e=a(d));return e}var a=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("chrome")){var a=(a=a.match(/chrome\/(\d+)/))?a[1]:-1,d=window.document,f="track"in d.createElement("track"),d="scoped"in d.createElement("style"),e="v8Locale"in window,n=document.createElement("canvas"),
m="seamless"in document.createElement("iframe"),p=w;try{n.getContext("webgl")&&(p=s)}catch(v){}if(n=b())return"fast"===n.type?7:1;if(!p&&"31"===a)return 1;if(!(m=(m||!p)&&"38"===a))if(m=f)if(m=!d)if(m=!e){var k;a:{m=window.navigator.mimeTypes;for(k in m)if("application/vnd.chromium.remoting-viewer"===m[k].type){k=s;break a}k=w}m=!k&&46>+a}if(m)return 7;if(f&&d&&e)return 1}return-1}();return h.Ua=a})();
(function(){function b(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.ca.hb()+","+h.ca.fb();h.c.j()}}function a(){clearTimeout(x);var d;z&&(d="visible"==document[z]);u&&(d=!document[u]);m="undefined"==typeof d?s:d;if((!n||!p)&&m&&v)y=s,l=+new Date;else if(n&&p&&(!m||!v))y=w,q+=+new Date-l;n=m;p=v;x=setTimeout(a,100)}function g(a){var l=document,d="";if(a in l)d=a;else for(var b=["webkit","ms","moz","o"],u=0;u<b.length;u++){var e=b[u]+a.charAt(0).toUpperCase()+a.slice(1);if(e in l){d=
e;break}}return d}function d(l){if(!("focus"==l.type||"blur"==l.type)||!(l.target&&l.target!=window))v="focus"==l.type||"focusin"==l.type?s:w,a()}var f=mt.event,e=h.G,n=s,m=s,p=s,v=s,k=+new Date,l=k,q=0,y=s,z=g("visibilityState"),u=g("hidden"),x;a();(function(){var l=z.replace(/[vV]isibilityState/,"visibilitychange");f.d(document,l,a);f.d(window,"pageshow",a);f.d(window,"pagehide",a);"object"==typeof document.onfocusin?(f.d(document,"focusin",d),f.d(document,"focusout",d)):(f.d(window,"focus",d),
f.d(window,"blur",d))})();h.ca={hb:function(){return+new Date-k},fb:function(){return y?+new Date-l+q:q}};e.d("pv-b",function(){f.d(window,"unload",b())});e.d("duration-send",b());e.d("duration-done",function(){l=k=+new Date;q=0});return h.ca})();
(function(){var b=mt.lang,a=h.z,g=h.load,d={wb:function(d){if((window._dxt===r||b.e(window._dxt,"Array"))&&"undefined"!==typeof h.c){var e=h.c.Q();g([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(e)].join(""),d)}},Jb:function(a){if(b.e(a,"String")||b.e(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Xa=d})();
(function(){function b(a,d,b,e){if(!(a===r||d===r||e===r)){if(""===a)return[d,b,e].join("*");a=String(a).split("!");for(var u,x=w,f=0;f<a.length;f++)if(u=a[f].split("*"),String(d)===u[0]){u[1]=b;u[2]=e;a[f]=u.join("*");x=s;break}x||a.push([d,b,e].join("*"));return a.join("!")}}function a(l){for(var b in l)if({}.hasOwnProperty.call(l,b)){var e=l[b];d.e(e,"Object")||d.e(e,"Array")?a(e):l[b]=String(e)}}var g=mt.url,d=mt.lang,f=mt.o,e=mt.i,n=h.z,m=h.G,p=h.Xa,v=h.load,k={N:[],W:0,Ea:w,w:{qa:"",page:""},
init:function(){k.g=0;m.d("pv-b",function(){k.Ya();k.$a()});m.d("pv-d",function(){k.ab();k.w.page=""});m.d("stag-b",function(){h.c.b.api=k.g||k.W?k.g+"_"+k.W:"";h.c.b.ct=[decodeURIComponent(h.c.getData("Hm_ct_"+c.id)||""),k.w.qa,k.w.page].join("!")});m.d("stag-d",function(){h.c.b.api=0;k.g=0;k.W=0})},Ya:function(){var a=window._hmt||[];if(!a||d.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,l=0;l<arguments.length;l++){var b=arguments[l];d.e(b,"Array")&&(a.cmd[a.id].push(b),
"_setAccount"===b[0]&&(1<b.length&&/^[0-9a-f]{32}$/.test(b[1]))&&(b=b[1],a.id=b,a.cmd[b]=a.cmd[b]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},$a:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var d=a.cmd[c.id],b=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,u=d.length;e<u;e++){var x=d[e];b.test(x[0])?k.N.push(x):k.na(x)}a.cmd[c.id]={push:k.na}},ab:function(){if(0<k.N.length)for(var a=0,d=k.N.length;a<d;a++)k.na(k.N[a]);k.N=t},na:function(a){var b=a[0];if(k.hasOwnProperty(b)&&
d.e(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(k.g|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||s===a))k.g|=2,h.c.Aa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){k.g|=4;h.c.b.sn=h.c.za();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=e.S()+e.L();h.c.b.kb=0;h.c.ha?(h.c.b.nv=0,h.c.b.st=4):h.c.ha=s;var d=h.c.b.u,b=h.c.b.su;h.c.b.u=n.protocol+"//"+document.location.host+a[1];k.Ea||(h.c.b.su=document.location.href);
h.c.j();h.c.b.u=d;h.c.b.su=b;h.c.B=+new Date}},_trackEvent:function(a){2<a.length&&(k.g|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.h(a[1])+"*"+d.h(a[2])+(a[3]?"*"+d.h(a[3]):"")+(a[4]?"*"+d.h(a[4]):""),h.c.j())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){k.W++;for(var f=(h.c.b.cv||"*").split("!"),u=f.length;u<b-1;u++)f.push("*");f[b-1]=e+"*"+d.h(a[2])+"*"+d.h(a[3]);h.c.b.cv=f.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.c.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.c.Cb("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.h(a[1]);a=d.h(a[2]);if(e!==r&&a!==r){var f=decodeURIComponent(h.c.getData("Hm_ct_"+c.id)||""),f=b(f,e,1,a);h.c.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var e=d.h(a[1]);a=d.h(a[2]);if(e!==r&&a!==r){var f=k.w.qa,f=b(f,e,2,a);k.w.qa=f}}},_setPageTag:function(a){if(!(3>a.length)){var e=d.h(a[1]);a=d.h(a[2]);
if(e!==r&&a!==r){var f=k.w.page,f=b(f,e,3,a);k.w.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],k.Ea=s)},_trackOrder:function(b){b=b[1];d.e(b,"Object")&&(a(b),k.g|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=f.stringify(b),h.c.j())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.g|=32,h.c.b.et=93,h.c.b.ep=a,h.c.j()},_trackRTPageview:function(b){b=b[1];d.e(b,"Object")&&
(a(b),b=f.stringify(b),512>=encodeURIComponent(b).length&&(k.g|=64,h.c.b.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.e(b,"Object")){a(b);b=encodeURIComponent(f.stringify(b));var e=function(a){var b=h.c.b.rt;k.g|=128;h.c.b.et=90;h.c.b.rt=a;h.c.j();h.c.b.rt=b},g=b.length;if(900>=g)e.call(this,b);else for(var g=Math.ceil(g/900),m="block|"+Math.round(Math.random()*n.V).toString(16)+"|"+g+"|",u=[],x=0;x<g;x++)u.push(x),u.push(b.substring(900*x,900*x+900)),e.call(this,m+u.join("|")),u=[]}},_setUserId:function(a){a=
a[1];p.wb();p.Jb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||s===a))h.c.Ba=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||s===a))h.c.M=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.j())):m.F("duration-send");m.F("duration-done")},_require:function(a){1<a.length&&(a=a[1],n.Ra.test(g.K(a))&&v(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1];a=a[2];if(d.H(n.Ga,e)&&d.e(a,"Function")&&
(b.plugins=b.plugins||{},b.C=b.C||{},b.plugins[e]=a,b.s=b.s||[],a=b.s.slice(),e&&a.length&&a[0][1]===e))for(var f=0,u=a.length;f<u;f++){var x=a[f][2]||{};if(b.plugins[e]&&!b.C[e])b.C[e]=new b.plugins[e](x),b.s.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],f=a[2]||{};if(d.H(n.Ga,e))if(b.plugins=b.plugins||{},b.C=b.C||{},b.plugins[e]&&!b.C[e])b.C[e]=new b.plugins[e](f);else{b.s=b.s||[];for(var f=0,u=b.s.length;f<u;f++)if(b.s[f][1]===e)return;b.s.push(a);k._require([t,
n.zb+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=d.h(a[1]),e="";a=a[2];if(d.e(a,"Object")){var e=[],f;for(f in a)a.hasOwnProperty(f)&&(e.push(d.h(f)),e.push(d.h(a[f])));e="*"+e.join("*")}h.c.b.et=7;h.c.b.ep="ce!_iden*"+b+e;h.c.j()}}};k.init();h.Sa=k;return h.Sa})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.b={},this.Ba=this.Aa=s,this.M=l.M,this.ua=f.ia()&&0<c.aet.length?c.aet.split(","):"",this.ha=w,this.init())}var a=mt.url,g=mt.Ka,d=mt.oa,f=mt.lang,e=mt.cookie,n=mt.i,m=mt.localStorage,p=mt.sessionStorage,v=mt.o,k=mt.event,l=h.z,q=h.Ua,y=h.load,z=h.G;b.prototype={ka:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},
Fa:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},T:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.Fa(b,c.dm[d]))return s}else{var e=a.K(b);if(e&&this.ka(e,c.dm[d]))return s}return w},Q:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.ka(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ea:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.Fa(document.location.href,
d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"},lb:function(){if(!document.referrer)return l.D-l.I>c.vdur?1:4;var b=w;this.T(document.referrer)&&this.T(document.location.href)?b=s:(b=a.K(document.referrer),b=this.ka(b||"",document.location.hostname));return b?l.D-l.I>c.vdur?1:4:3},getData:function(a){try{return e.get(a)||p.get(a)||m.get(a)}catch(b){}},setData:function(a,b,d){try{e.set(a,b,{domain:this.Q(),path:this.ea(),J:d}),d?m.set(a,b,d):p.set(a,b)}catch(f){}},Cb:function(a){try{e.set(a,
"",{domain:this.Q(),path:this.ea(),J:-1}),p.remove(a),m.remove(a)}catch(b){}},Hb:function(){var a,b,d,f,g;l.I=this.getData("Hm_lpvt_"+c.id)||0;13===l.I.length&&(l.I=Math.round(l.I/1E3));b=this.lb();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){f=d.split(",");for(g=f.length-1;0<=g;g--)13===f[g].length&&(f[g]=""+Math.round(f[g]/1E3));for(;2592E3<l.D-f[0];)f.shift();g=4>f.length?2:3;for(1===a&&f.push(l.D);4<f.length;)f.shift();d=f.join(",");f=f[f.length-1]}else d=l.D,f="",g=1;this.setData("Hm_lvt_"+
c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,l.D);d=e.xb(this.Q(),this.ea());if(0===c.nv&&this.T(document.location.href)&&(""===document.referrer||this.T(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=f;this.b.lv=g},Gb:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=l.La.length;e<f;e++){var g=l.La[e],k=this.b[g];"undefined"!==typeof k&&""!==k&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(k))}switch(b){case 0:this.b.rt&&
a.push("rt="+encodeURIComponent(this.b.rt));break;case 5:a.push("_lpt="+this.B);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.B);a.push("_ct="+d);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},Ib:function(){this.Hb();this.b.si=c.id;this.b.sn=this.za();this.b.su=document.referrer;this.b.hh=window.location.hash;this.b.ds=n.Db;this.b.cl=n.colorDepth+"-bit";this.b.ln=String(n.language).toLowerCase();this.b.ja=n.javaEnabled?1:0;this.b.ck=n.cookieEnabled?1:0;this.b.bs=q;this.b.lo=
"number"===typeof _bdhm_top?1:0;this.b.fl=d.nb();this.b.v="1.2.51";this.b.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=n.S()+n.L();var b=document.location.href;this.b.cm=a.m(b,l.rb)||"";this.b.cp=a.m(b,l.tb)||a.m(b,l.Nb)||"";this.b.cw=a.m(b,l.qb)||a.m(b,l.Pb)||"";this.b.ci=a.m(b,l.ob)||a.m(b,l.Mb)||"";this.b.cf=a.m(b,l.ub)||a.m(b,l.Ob)||"";this.b.cu=a.m(b,l.pb)||a.m(b,l.Lb)||""},init:function(){try{this.Ib(),0===this.b.nv?this.Fb():this.wa(),h.c=this,
this.Wa(),this.Va(),z.F("pv-b"),this.Eb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));g.log(l.la+"//"+l.Ha+"?"+b.join("&"))}},Eb:function(){function a(){z.F("pv-d")}this.Aa?(this.ha=s,this.b.et=0,this.b.ep="",this.b.vl=n.S()+n.L(),this.j(a)):a();this.B=+new Date},j:function(a){if(this.Ba){var b=this;b.b.rnd=Math.round(Math.random()*l.V);z.F("stag-b");var d=l.la+"//"+l.Ha+
"?"+b.Gb();z.F("stag-d");b.Qa(d);g.log(d,function(d){b.Ia(d);f.e(a,"Function")&&a.call(b)})}},Wa:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.K(document.referrer)===l.Ma?1:0,f=a.m(b,"jn"),g=/^heatlink$|^select$|^pageclick$|^customevent$/.test(f);b&&(d.test(b)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*l.V),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",l.protocol+"//"+c.js+f+".js?"+this.b.rnd),
f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},Va:function(){if(window.postMessage&&window.self!==window.parent){var b=this;k.d(window,"message",function(d){if(a.K(d.origin)===l.Ma){var e=d.data||{};d=e.sd||"";var e=e.jn||"",f=/^customevent$/.test(e);RegExp(c.id).test(d)&&f&&(b.b.rnd=Math.round(Math.random()*l.V),y(l.protocol+"//"+c.js+e+".js?"+b.b.rnd))}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},Qa:function(a){var b;
try{b=v.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);p.set("Hm_unsent_"+c.id,v.stringify(b))},Ia:function(a){var b;try{b=v.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?p.set("Hm_unsent_"+c.id,v.stringify(b)):this.wa()}},wa:function(){p.remove("Hm_unsent_"+
c.id)},Fb:function(){var a=this,b;try{b=v.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var e=function(b){g.log(l.la+"//"+b,function(b){a.Ia(b)})},f=0;f<b.length;f++)e(b[f])},za:function(){return Math.round(+new Date/1E3)%65535}};return new b})();
(function(){var b=mt.event,a=mt.lang,g=h.z;if(c.kbtrk&&"undefined"!==typeof h.c){h.c.b.kb=a.Da(h.c.b.kb)?h.c.b.kb:0;var d=function(){h.c.b.et=85;h.c.b.ep=h.c.b.kb;h.c.j()};b.d(document,"keyup",function(){h.c.b.kb++});b.d(window,"unload",function(){d()});setInterval(d,g.yb)}})();var B=h.z,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.i,a=mt.lang,g=mt.event,d=mt.o;if("undefined"!==typeof h.c&&(c.med||(!b.Ca||7<b.vb)&&c.cvcc)){var f,e,n,m,p=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},v=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},k=function(b,e){var g={};g.n=f;g.t="clk";g.v=b;if(e){var k=e.getAttribute("href"),l=e.getAttribute("onclick")?""+e.getAttribute("onclick"):t,m=e.getAttribute("id")||"";n.test(k)?(g.sn="mediate",
g.snv=k):a.e(l,"String")&&n.test(l)&&(g.sn="wrap",g.snv=l);g.id=m}h.c.b.et=86;h.c.b.ep=d.stringify(g);h.c.j();for(g=+new Date;400>=+new Date-g;);};if(c.med)e="/zoosnet",f="swt",n=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(n.test(e)||n.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){e="/other-comm";f="other";n=c.cvcc.q||r;var l=c.cvcc.id||r;m={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f,g=0,k=b.length;g<k;g++)d=b[g],n!==r?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),l?(d=d.getAttribute("id"),(n.test(e)||n.test(f)||l.test(d))&&
a.push(b[g])):(n.test(e)||n.test(f))&&a.push(b[g])):l!==r&&(d=d.getAttribute("id"),l.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof n){var q;e+=/\/$/.test(e)?"":"/";var y=function(b,d){if(q===d)return k(e+b,d),w;if(a.e(d,"Array")||a.e(d,"NodeList"))for(var f=0,g=d.length;f<g;f++)if(q===d[f])return k(e+b+"/"+(f+1),d[f]),w};g.d(document,"mousedown",function(b){b=b||window.event;q=b.target||b.srcElement;var d={};for(v(m,function(b,e){d[b]=a.e(e,"Function")?e():document.getElementById(e)});q&&
q!==document&&v(d,y)!==w;)q=q.parentNode})}}})();(function(){var b=mt.f,a=mt.lang,g=mt.event,d=mt.o;if("undefined"!==typeof h.c&&a.e(c.cvcf,"Array")&&0<c.cvcf.length){var f={Oa:function(){for(var a=c.cvcf.length,d,m=0;m<a;m++)(d=b.xa(decodeURIComponent(c.cvcf[m])))&&g.d(d,"click",f.da())},da:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=d.stringify(a);h.c.j()}}};b.Ab(function(){f.Oa()})}})();
(function(){var b=mt.event,a=mt.o;if(c.med&&"undefined"!==typeof h.c){var g=+new Date,d={n:"anti",sb:0,kb:0,clk:0},f=function(){h.c.b.et=86;h.c.b.ep=a.stringify(d);h.c.j()};b.d(document,"click",function(){d.clk++});b.d(document,"keyup",function(){d.kb=1});b.d(window,"scroll",function(){d.sb++});b.d(window,"unload",function(){d.t=+new Date-g;f()});b.d(window,"load",function(){setTimeout(f,5E3)})}})();c.spa!==r&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]));})();
